name: CI
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate JSON files
        run: |
          set -e
          find schemas -name "*.json" -print0 | xargs -0 -I{} python -m json.tool {}

      - name: Ruff (lint)
        run: |
          pip install ruff
          ruff check .

      - name: Run tests with pytest
        env:
          LLM_MOCK: "1"
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest -v --cov=src --cov=backend --cov-report=term-missing --cov-report=xml --cov-report=html

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: always()
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
        continue-on-error: true

      - name: Archive coverage results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: htmlcov/
          retention-days: 30
